version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: food-delivery-postgres
    environment:
      POSTGRES_DB: food_delivery-db
      POSTGRES_USER: mostafa
      POSTGRES_PASSWORD: mostafa123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - food_delivery-network


  redis:
    image: redis:7-alpine
    container_name: food-delivery-redis
    ports:
      - "6379:6379"
    networks:
      - food_delivery-network
  

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: food-delivery-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - food_delivery-network
  
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: food-delivery-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - food_delivery-network
    ports:
      - "9092:9092"

volumes:
  postgres-data:

networks:
  food_delivery-network:
    driver: bridge
